### ISSUE TITLE
Hand test mode refinements

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#110]
Based on summaries by Naim. These are _possible_ enhancements.

- [x] The opponent's deck
- [x] Starting number of cards
- [x] Shuffle deck or not
- [ ] Life Points? (These don't count in the mode anyway)
- [x] Saving replays?

These could already be controlled in Lua like so
```lua
Debug.SetPlayerInfo(int playerid, int lp, int startcount, int drawcount, [bool shuffle], deck)
--opponent deck
Debug.SetPlayerInfo(1,8000,5,1,true,"./deck/HandTestDummy")
--don't shuffle your deck
Debug.SetPlayerInfo(0,8000,5,1,false,nil)
```

**Comment by feuerpanda** [comment]
Possible enhancement would also be to use different rulesets. Many Rulesets dont have the same field and rules (like draw limits and summoning).
