### ISSUE TITLE
Repository management refactoring

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#127]
- [x] Replace the overloaded pairs of vectors with proper structs
- [x] Add support for a warning field for the network/fetch error and externalize that string
- [ ] Fix the `O(n^2)` runtime iterating over both `working_repos` and `available_repos`

**Comment by LordYuuma** [comment]
W.r.t. the _O(n^2)_ runtime, would something like the following work?

```cpp
std::vector<const GitRepo*> RepoManager::GetReadyRepos() {
        std::vector<const GitRepo*> res;
        for(auto repo = available_repos.begin(); it != available_repos.end();) {
                auto working_repo = working_repos.find((*repo)->repo_path);
                if (working_repo->second.wait_for(std::chrono::milliseconds(0)) == std::future_status::ready) {
                        auto results = working_repo->second.get();
                        (*repo)->error = results.error;
                        (*repo)->warning = results.warning;
                        (*repo)->commit_history_full = results.full_history;
                        (*repo)->commit_history_partial = results.partial_history;
                        (*repo)->ready = true;
                        working_repos.erase(working_repo);

                        res.push_back(*repo);
                        repo = available_repos.erase(repo);
                }
                else
                        repo++;
        }
        return res;
}
```

We walk through all available repos, which has runtime _O(n)_.  `map::find` has _O(log n)_, `erase(iterator)` _O(1)_, the other work is constant per-repo effort.  Thus we have a final runtime of _O(nlog n)_, which is about as good as we can get for two containers.  If you had only one, you could get _O(n)_ by using tuples.  I'm not sure whether tuples would work out for you, however.

Note, that I have neither compiled nor tested this code, so typos may hide in there and it probably needs some error handling around `working_repo`.

**Comment by edo9300** [comment]
https://github.com/edo9300/edopro/commit/ec9aa92773e26c4332bbe89dde351843667a0040#diff-83cd0fc8532b2c5dc47bd43c84059043b64416bc0ea9e01f76a8ba55e51c362c
