### ISSUE TITLE
Siding message still displayed after a BO3 ended

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#136]
Situation: BO3 concluded, player opted to rematch but opponent declined. Result:

![Siding text](https://cdn.discordapp.com/attachments/586821870070792223/696529547235033148/unknown.png)

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/edopro/commit/7745aba50f8e2ec72ec716b0c74819e2618031f1
