### ISSUE TITLE
Compilation of possibly network protocol associated bugs from day 1

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#137]
I have not had the time to reproduce any of this cases and isolate the fault points.

- [x] rematches seem to sometimes crash the client
- [x] "Playing a tag duel with best of 3. During game 2, my partner's deck switched with mine. I have control of his deck and he has control of mine"
- [ ] "I've noticed an issue while dueling against the ai. Occasionally, when dueling in a best 2 out of 3 match, the duels won't end when the player or the ai has won twice, and will instead just keep restarting the round over and over."
- [x] "just crashed in tag duel when turn switched to my teammate while viewing my own extra deck"
- [x] "crashes on hol;ding priority when looking at grave during opponents turn...gamebreaking af"

**Comment by edo9300** [comment]
4 and 5 should be fixed in this commit https://github.com/edo9300/edopro/commit/efebd81f0c28b08e32381e3c387f2c43c4303262

**Comment by edo9300** [comment]
1 should be fixed in https://github.com/edo9300/edopro/commit/3e820a319f48a359a26650cb7fa75172e51351cd

**Comment by edo9300** [comment]
Fixed 2 with https://github.com/edo9300/edopro/commit/903db367af66a627dc3ec4acf140cdb458c20d36 and https://github.com/edo9300/edopro/commit/202e06241c47d3ab0f86815a194ef6f7dea6524d

**Comment by edo9300** [comment]
Fixed 3 in https://github.com/edo9300/edopro/commit/c4a351360f390d6c8afdc7a9b5f468cfa82bce97
