### ISSUE TITLE
Incorrect Settings Loaded for Chat Mute Options

### ISSUE THREAD

**Issue by Zeph72** [edo9300/edopro#143]
When settings are loaded from system.conf on program launch, the value for 'mute_spectators' is applied to the mute opponent setting instead. This seems to also result in the setting for muting spectators to fall back to a default value of `false`.

The offending line is 134 here:
https://github.com/edo9300/edopro/blob/f50d6869388f37f4f5dd9f4ca3201d6f151c4221/gframe/game_config.cpp#L131-L134

Thanks!

**Comment by kevinlul** [comment]
Hi there! Great catch. If you're interested in fixing this, you can submit a pull request! Otherwise I will get around to it when I have time.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/edopro/commit/45c1ee56849f9ba10ed78310c652723b95dc8f4a
