### ISSUE TITLE
[Linux] Compilation issue - irrlicht

### ISSUE THREAD

**Issue by 0x1BADC0DE** [edo9300/edopro#146]
Getting compile issues suggesting an irrlicht version problem (1.8.4): [image](https://i.imgur.com/VhqqZ5m.png)
What version are you guys using?

Used "vcpkg install irrlicht" by the way which is not mentioned in the wiki, I'm on manjaro.
It compiles fine up until that point shown in the image.

**Comment by kevinlul** [comment]
Hey there, we're actually using a fork of Irrlicht because it has severe issues with clipboard handling and some missing features. https://github.com/edo9300/irrlicht1-8-4

The documentation hasn't been updated to reflect this because we've been so busy.
