### ISSUE TITLE
Update libgit2 forward declarations

### ISSUE THREAD

**Issue by LordYuuma** [edo9300/edopro#148]
Instead of 
```cpp
// libgit2 forward declarations
struct git_repository;
#if LIBGIT2_VER_MINOR==99
struct git_indexer_progress;
#else
struct git_transfer_progress;
using git_indexer_progress = git_transfer_progress;
#endif
```
use something more future-proof like
```cpp
// libgit2 forward declarations
struct git_repository;
#if LIBGIT2_VER_MAJOR>0 || LIBGIT2_VER_MINOR>=99
struct git_indexer_progress;
#else
struct git_transfer_progress;
using git_indexer_progress = git_transfer_progress;
#endif
```

**Comment by kevinlul** [comment]
Did you update to [1.0.0 "Luftschloss"](https://github.com/libgit2/libgit2/releases/tag/v1.0.0) already?

**Comment by LordYuuma** [comment]
Guix packages 1.0.0 "Luftschloss" since https://github.com/guix-mirror/guix/commit/912b6ab01c405f693470ccb0c86a5e652674529a.  According to the release notes, 1.0.0. should be backwards compatible, but I can't confirm this, since I don't use the feature.  I do use https://github.com/LordYuuma/guix-ygopro/commit/01f3032b409553e5fc58dcd321cc14ab3950be13 to make edopro build, because I haven't disabled the repository feature (yet).
