### ISSUE TITLE
Relay replays crash if started on turns after a player change

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#149]
[Example 10-turn 3v3 relay](https://cdn.discordapp.com/attachments/420315022632157193/697968350440980579/help.yrpX)

A player change occurs on turn 5. Attempting to start the replay in yrp or yrpX mode from turn 5 or later results in a client crash. An abort is called either while locking the main mutex [at duelclient.cpp:3960](https://github.com/edo9300/edopro/blob/master/gframe/duelclient.cpp#L3960) or immediately after in another thread; the next line is never reached.

**Comment by edo9300** [comment]
Fixed in de3b38df2f15aefef2864395f1bd6f7ae4b0e631
