### ISSUE TITLE
./travis/quickrun.sh debug|release command won't work

### ISSUE THREAD

**Issue by Tsuyo99** [edo9300/edopro#158]
Hey! 

The "./travis/quickrun.sh debug|release" command doesnt work in step 4 of this tutorial: https://github.com/edo9300/edopro/wiki/4.-Running

Here is a screenshot of the problem:
![download](https://user-images.githubusercontent.com/62599533/79669503-3dddc400-81bc-11ea-9e63-5854ad4d68b0.png)

Also in text:
$ ./travis/quickrun.sh release
+ DESTINATION=bin/debug
+ cp '*.conf' bin/debug
cp: cannot stat '*.conf': No such file or directory

$ ./travis/quickrun.sh debug
+ DESTINATION=bin/debug
+ cp '*.conf' bin/debug
cp: cannot stat '*.conf': No such file or directory

won't work with any of those commands :(

**Comment by kevinlul** [comment]
Quickrun is an outdated script that I haven't gotten around to updating

**Comment by Tsuyo99** [comment]
Thanks for the fast response!

How will I resolve the issue?

**Comment by Tsuyo99** [comment]
My vs2017 wont run the exe and I thought that the problem would probably revolve around the "./travis/quickrun.sh debug|release" command

**Comment by kevinlul** [comment]
![image](https://user-images.githubusercontent.com/6320810/79669641-e8d58a00-818a-11ea-9591-f45a05503594.png)

Set this to your Project Ignis folder or equivalent. It's probably crashing due to missing fonts and configs.

**Comment by Tsuyo99** [comment]
Output from vs2017 debug:

The thread 0x539c has exited with code 0 (0x0).
Exception thrown at 0x76BC4192 in ygopro.exe: Microsoft C++ exception: nlohmann::detail::parse_error at memory location 0x021ABFDC.
Exception thrown at 0x76BC4192 in ygopro.exe: Microsoft C++ exception: std::exception at memory location 0x021AD390.
The thread 0x2818 has exited with code 1 (0x1).
The thread 0x3ab4 has exited with code 1 (0x1).
The program '[23100] ygopro.exe' has exited with code 1 (0x1).

Did as you said, that's what pops up once again :(

**Comment by LordYuuma** [comment]
Judging from the error, it seems that nlohmann barfs at either of your configuration JSONs (there should be one in config and one for Windbot).  A working, albeit meaningless `config/configs.json` would be:

```json
{
    "repos": [],
    "urls": [],
    "servers": []
}
```
You can safely delete/move away the WindBot JSON, it will only cause a warning if missing.  Once you find out which of the files causes the error, you can try repairing that file.
