### ISSUE TITLE
More automatic updates

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#162]
Not exhaustive nor required
- [x] Externalize strings
- [x] Move update prompt to centre
- [x] Extraction progress bars (c3bc6b423a0dd6ce9469d94978307320be410b23)
- [x] Warning prompt for potential overwrites?
- [ ] Backups?
- [x] Extra user config json that will never be overwritten (820235804c5a6b308971be0c6fd040dafe2386a1)
- [x] Display changelog on restart
- [x] use the same user agent for fetching the roomlist instead of `YGOPRO`
- [ ] Fetch server list at runtime
- [x] "Couldn't load ocgcore" conflicts with the update prompt, soft-locking the client
- [x] Disable update checking via config and checkbox

**Comment by edo9300** [comment]
also worth adding, changelog viewing on restart

**Comment by kevinlul** [comment]
Feature-complete.

**Comment by kevinlul** [comment]
Closed with 533dc0de5a1b4893301aff9bb1fc734041a4f953
