### ISSUE TITLE
Sum of Attack

### ISSUE THREAD

**Issue by jefreestyles** [edo9300/edopro#163]
It would be nice to see the total Attack that you have on your field.  Instead of having to open a calculator and wasting time.  This would be helpful when you want to do an OTK.

Although a calc would be needed if your opponent still has some monsters.

**Comment by kevinlul** [comment]
This issue tracker is not your soapbox.

**Comment by jefreestyles** [comment]
Hi Kevin, where can I post suggestions for EDOPro?  I tried Discord but no one responded.

**Comment by kevinlul** [comment]
That's because, as we described in our [initial announcement](https://www.reddit.com/r/yugioh/comments/fvdn7v/presenting_project_ignis_edopro_the_opensource/), we are not taking feature suggestions. Feel free to open a pull request and I can review it when I get the time!
