### ISSUE TITLE
Protocol change: deck errors

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#164]
It has been known since 79ebf941b19379b0d9a79658fc02a7405902526a that card IDs above 2^28 will not be displayed in the error message and just display "Invalid Deck". This is because the upper four bits of the error message contain a deck error code instead of the entire four bytes being used for a passcode. The correct fix would be to change the error message protocol to add another byte after these four bytes for the error code. ~~but we know how fun the network protocol is~~

The 28 bitshift was introduced in upstream 2049.

**Comment by edo9300** [comment]
The deck error messages were updated here https://github.com/edo9300/edopro/commit/f9e07fac73ac4bc22316c5c6d075b8358b27cc3d
