### ISSUE TITLE
[Linux] Linking issue (libgit2, libcurl)

### ISSUE THREAD

**Issue by 0x1BADC0DE** [edo9300/edopro#165]
Compiling goes fine now, linking does not: [image](https://imgur.com/GFSuQWP)
Using Manjaro.

**Comment by kevinlul** [comment]
We don't use LibSSH since the use case doesn't come up. You can try disabling that backend when compiling libgit2 and libcurl to mirror our approach. If you want SSH support, you can add the linker flags to link it, since it's not finding the symbols.

**Comment by 0x1BADC0DE** [comment]
Thanks, but what exactly do you mean by 'mirror our approach'? There's little accurate information available as far as I can see regarding building from source. Not too familiar with this build process either yet (coming from Visual Studio).

**Comment by kevinlul** [comment]
Are those dependencies provided by your package manager or through vcpkg?

**Comment by 0x1BADC0DE** [comment]
The dependencies with exception of Irrlicht are provided by vcpkg.

If I turn off the BUILD_SHARED_LIBS and USE_SSH flags so it actually compiles statically (libgit2.a) without SSH use, and put that file manually in /usr/share/vcpkg/installed/x64-linux/debug/lib where edopro expects that file to be, I get the following: [image](https://imgur.com/mVpwdRO)

**Comment by edo9300** [comment]
That linking issue is because by default libgit2 now use pcre as regex engine, you have to set REGEX_BACKEND to use the builtin engine

**Comment by 0x1BADC0DE** [comment]
Thanks that worked along with deleting CMakeCache.txt and rebuilding.
Compiles and links fine now.
