### ISSUE TITLE
Win messages and replays

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#166]
This is regarding the `showcardcode` You Win/You Lose overlay text at the end of a replay.

If a player surrenders, the text is shown in `yrpX` mode but not shown in `yrp` mode. [Example](https://cdn.discordapp.com/attachments/420315022632157193/703634648063803542/2020-04-25_11-48-43.yrpX)

If a player wins by reducing LP to 0, the text is not shown in `yrpX` mode but is shown in `yrp` mode. [Example](https://cdn.discordapp.com/attachments/420315022632157193/703634687154978896/2020-04-25_11-51-02_W.yrpX)

I think this has to do with what packets are saved between old and new replay mode.

**Comment by edo9300** [comment]
The issue with victory reasons not being recorded in yrpX has been fixed here 22d51d8210c7f83621bef3ee938ae46441dcab29, for the yrp issue, that's a flaw of that replay format, those victory conditions aren't decided by the gamestate, so they cannot be represented in there without altering the replay format
