### ISSUE TITLE
Exiting EDOPro at the end of a duel freezes the application

### ISSUE THREAD

**Issue by FelixRilling** [edo9300/edopro#168]
At the end of a duel (only tested locally against AI), where the "Save Replay" dialog is shown, if I exit the application (in my case running KDE by clicking the "X" in the title bar or the task bar), the application freezes, neither closing nor being responsive to any input. Weird graphic glitches occur afterwards when resizing the window (
![image](https://user-images.githubusercontent.com/3207763/80407405-dd3e3d80-88c5-11ea-8a9b-263959f0160b.png)).
Closing the application in any other situation seems to work.
No errors are written to the shell session I started EDOPro through.

System:
archlinux
kde 5.18.4
xorg-server 1.20.8-1
mesa 20.0.4-2 / opengl 4.6

**Comment by kevinlul** [comment]
Confirmed for sure on Arch Linux, but not macOS or Windows.

**Comment by edo9300** [comment]
Fixed here https://github.com/edo9300/edopro/commit/69e09ad50f314d461383f821da06f786cbdac5c4
