### ISSUE TITLE
Question regarding Base64 Deck URIs.

### ISSUE THREAD

**Issue by FelixRilling** [edo9300/edopro#171]
I am the author of [yugioh-deck-tool](https://github.com/FelixRilling/yugioh-deck-tool), a web application that more or less mimics the deck builder of EDOPro.
I was wondering if there is some form of loose specification for Base64 Deck URIs EDOPro uses (The structure of `ydke://foo!bar!fizz`) so that myself and authors of different tools which currently consume `.ydk` files can make use of those URIs as well.

Only somewhat related, but I currently have a similar feature which however only targets encoding to individual URL query parameters (<https://github.com/FelixRilling/yugioh-deck-tool/blob/development/packages/core/src/core/business/service/DeckUriEncodingService.ts>).

**Comment by edo9300** [comment]
ydke structure is pretty simple, it consists if 3 base 64 strings identifying relatively deck, extra and side, separated by ``!`` (as it's not part of the base64 alphabet, those base64 strings represent an array of ints consisting of the card codes, you can find a ts implementation of the parsing [here](https://github.com/AlphaKretin/bastion-bot/commit/0349cdced8ad2d2de5c4758ea7312197505e94ef)

**Comment by AlphaKretin** [comment]
Just for the record, I don't have any issue with that code being used as a reference. 👍 The relevant bit is the `ToPasscodes` function, once you've extracted the three segments.

**Comment by FelixRilling** [comment]
Thank you for the help and the reference!
