### ISSUE TITLE
Music loops regardless of setting

### ISSUE THREAD

**Issue by LordYuuma** [edo9300/edopro#173]
v38.0.2 should have introduced a user setting to loop music, but this setting is not respected.   f9534ae043cddc5b1da081b7c2fec4d4b3f0f911 inadvertently dropped the parameter to the `PlayBGM` calls, which assume `true` as default.

**Comment by edo9300** [comment]
Thanks for pointing it out, _this is what happens when your work folder is pretty messy and you have everyhting alltogether :sweat_smile:_. Fixed here 3404586bf6795b075bccb4ec106544d29a08ca35
