### ISSUE TITLE
Crash when shuffling back a banished monster that was originally face-up in the Extra Deck

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#176]
[Puzzle](https://cdn.discordapp.com/attachments/420315022632157193/705509679601680414/electrum_fucking_stupid.lua)

Steps to reproduce:
1. Mill one "Elemental HERO Electrum" with "Gale Dogra"
1. Banish that "Elemental HERO Electrum" with "Soul Release"
1. Activate "Chain Material" and "Fusion Gate" to Fusion Summon the other "Elemental HERO Electrum"
1. When the mandatory on-summon effect procs, the game will crash on shuffling the banished "Elemental HERO Electrum"

This occurs whether the banished Electrum was originally face-up or not.

Stacktrace
```
game.cpp:425 Game::DrawCard
game.cpp:419 Game::DrawCards
game.cpp:1712 Game::MainLoop
```
The ClientCard pointer in the `dField.extra` vector becomes a nullptr, resulting in a nullptr dereference.

Originally isolated by pyrQ 30/04/2020

**Comment by pyrQ** [comment]
To clarify, the crash happens even if you mill the "Elemental HERO Electrum" that is face-down in the Extra Deck.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro-core/commit/1aaa78ec819b100e25809208b41a502fd2edacc2
