### ISSUE TITLE
Anime card with wrong effect..

### ISSUE THREAD

**Issue by Puriss** [edo9300/edopro#177]
In edo ygopro, There is an anime card that has the wrong effect. If I explain the wrong card effect here and convince it, can you correct it with the correct card effect?? I can elaborate on what's wrong.

**Comment by edo9300** [comment]
This repository isn't the place to report wrong cards, if you think some effects might be wrong, report them on discord in the appropriate channel.

**Comment by Puriss** [comment]
I'm Sorry.
If so, where should I report the wrong card? I subscribed to github by looking at the website address listed on edoygo. If possible, I would like to talk directly to the anime card scripter. I have something important to say to him. If you know him, please connect me.
 
-----Original Message-----
