### ISSUE TITLE
Can't add a custom AI deck 

### ISSUE THREAD

**Issue by YousefSaber** [edo9300/edopro#190]
excuse me I was trying to add an AI deck downloaded from [YGOPRODECK](https://ygoprodeck.com/neo-seto-kaiba/) Neo Seto Kaiba deck renamed the file to `AI_NeoSetoKaiba.ydk` and put it in `C:\ProjectIgnis\WindBot\Decks` folder and in the `bots.json` file in the directory `C:\ProjectIgnis\WindBot` I wrote the script
```
{
  "name":"NeoSetoKaiba",
  "decK":"NeoSetoKaiba",
  "difficulty":1,
  "masterRules":[3,4,5]
},
```
the deck doesn't show in the AI menu what's wrong ?
here are some screenshots
![image](https://user-images.githubusercontent.com/33742499/83967846-5b2e3500-a8c5-11ea-9852-1baf02a4087e.png)
![image](https://user-images.githubusercontent.com/33742499/83967850-61241600-a8c5-11ea-9704-a0b6b6abbe05.png)

**Comment by kevinlul** [comment]
From the [contributing guidelines](https://github.com/edo9300/edopro#contributing):
> Please keep all usage questions and Windows and macOS bug reports on Discord; do not open an issue or pull request for this purpose. We are not taking suggestions or feature requests and the issue tracker is not to be used for this purpose either.

WindBot Ignite does not play your decks. This is not an advertised feature. If you would like to make a deck for it, consider submitting a pull request to https://github.com/ProjectIgnis/windbot/
