### ISSUE TITLE
Problem with a server and failures when compiling the client

### ISSUE THREAD

**Issue by Termita** [edo9300/edopro#191]
Hello, is there the possibility of uploading the dependencies for a compilation in a repo? I have tried to compile the client and failed. I have tried on Windows and Ubuntu without success.

I have also set up my own server, but I can only refresh the rooms, but I cannot create rooms, it throws me a version error. You should upgrade to "66.19 (ocgcore version 0.0)". And when I mount mycard's srv it just doesn't connect. Is there a model repository that works with the Project Ignis client?

IP server: 18.232.187.138
Port: 7911 and 7922

**Comment by knight00** [comment]
i compile client success, see wiki for detail steps.
and i think the server you compiled is not using edopro server branch?

To me, i compile client successful and worked.
However, for server, i cannot compile success in windows, said missing lua.h for ocgcore files.
While i added "includedir "../lua" " in ocgcore premake, another error said "unresolved external symbol _CrtDbgReport".
