### ISSUE TITLE
compile error on vs2017/2019: unrecognized flag  in 'p2' 

### ISSUE THREAD

**Issue by knight00** [edo9300/edopro#195]
![未命名](https://user-images.githubusercontent.com/16449813/92770392-7d57b780-f3cc-11ea-836f-888ec8863e21.png)
while compiling on vs2017/2019, the above error displays.
I have already installed v141_xp.
It happened only on release mode, debug mode is fine.
Any idea?

**Comment by edo9300** [comment]
If you used vcpkg, and have both vs2017 and vs2019 installed, the libraries could have been built with vs2019, making them incompatible, anyways, you can disable the v141_xp toolsed (that's only if you want to target windows xp, to disable it just remove that line from the premake file), then you should be able to compile it properly.

**Comment by knight00** [comment]
it worked, thank you
