### ISSUE TITLE
Lots of bugs coming out after using latest edopro git to compile

### ISSUE THREAD

**Issue by knight00** [edo9300/edopro#196]
Using the official release version to compile->no lua errors,
but, lots of lua bugs coming out after using latest edopro git to compile.

PS: I use release mode win10 to compile.
[error.log](https://github.com/edo9300/edopro/files/5328572/error.log)

**Comment by edo9300** [comment]
https://github.com/ProjectIgnis/CardScripts/commit/0295f680987d799dc5a97faa93349cde0ed58f99
