### ISSUE TITLE
Skin don't change

### ISSUE THREAD

**Issue by eduardogama1** [edo9300/edopro#201]
Since I installed the new update (39.0.0) i can't change screen's skin, can u fix that? I click on skins options, and when i gonna click to confirm the exchange, nothing happens and it still with the "automatic" gray skin, someone can help me with this?

**Comment by edo9300** [comment]
https://github.com/edo9300/edopro/commit/96a083acef7783aed67ce97aab7641b0f82acd6a

**Comment by eduardogama1** [comment]
???
________________________________
De: Edoardo Lolletti <notifications@github.com>
Enviado: segunda-feira, 28 de dezembro de 2020 07:32
Para: edo9300/edopro <edopro@noreply.github.com>
Cc: eduardogama1 <eu_edu@live.com>; Author <author@noreply.github.com>
Assunto: Re: [edo9300/edopro] Skin don't change (#201)


Closed #201<https://github.com/edo9300/edopro/issues/201>.

**Comment by eduardogama1** [comment]
And how i do it? And i forgot one thing: I can't see the cards, they don't have images, every card shows only a gray image distorted....
________________________________
De: Eduardo Carreira <eu_edu@live.com>
Enviado: segunda-feira, 28 de dezembro de 2020 14:06
Para: edo9300/edopro <reply@reply.github.com>
Assunto: RE: [edo9300/edopro] Skin don't change (#201)

???
________________________________
De: Edoardo Lolletti <notifications@github.com>
Enviado: segunda-feira, 28 de dezembro de 2020 07:32
Para: edo9300/edopro <edopro@noreply.github.com>
Cc: eduardogama1 <eu_edu@live.com>; Author <author@noreply.github.com>
Assunto: Re: [edo9300/edopro] Skin don't change (#201)


Closed #201<https://github.com/edo9300/edopro/issues/201>.
