### ISSUE TITLE
UI scaling too high

### ISSUE THREAD

**Issue by jeffythedragonslayer** [edo9300/edopro#205]
I accidentally typed an extra zero while trying to set the UI scale to 200% and now everything is so big I can't even see the settings gear icon in the bottom left.  How do I reset it?

![image](https://user-images.githubusercontent.com/13253146/108570643-6e125980-72dc-11eb-9785-82518d39ee1e.png)

**Comment by edo9300** [comment]
Change the dpi_scale setting in the system.conf file

**Comment by jeffythedragonslayer** [comment]
Thanks, that did the trick.
