### ISSUE TITLE
Clicking "Join" in "LAN + AI" crashes the application if no game is is hosted for the given data

### ISSUE THREAD

**Issue by FelixRilling** [edo9300/edopro#206]
EDOPro 39.0.3

Clicking "Join" in "LAN + AI" crashes the application if no game is is hosted for the given data. If one is hosted, everything works as expected.
Error message in console:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
zsh: abort (core dumped)  ./EDOPro
```
Additional Notes:
- It can be reproduced for me consistently.
- Weirdly enough, clicking  "Host" on the screen and Canceling, clicking "Join" shows the regular error message instead of crashing

Some additional data:
Kernel: Linux 5.11.7
Distro: Arch Linux
Mono JIT compiler version 6.12.0 

Please advise if the core dump should be attached

**Comment by edo9300** [comment]
If you have a core dump, that'd be helpful, as locally it doesn't seem to crash from my quick tests. (Also actually it isn't "no game selected" as join connects to the IP/port specified.)

**Comment by FelixRilling** [comment]
> If you have a core dump, that'd be helpful, as locally it doesn't seem to crash from my quick tests. (Also actually it isn't "no game selected" as join connects to the IP/port specified.)

Ah, right! Confused the UI with the Server View.

Here is the dump:
```
       Message: Process 41872 (EDOPro) of user 1000 dumped core.
                
                Stack trace of thread 42017:
                #0  0x00007fe1cbda2ef5 raise (libc.so.6 + 0x3cef5)
                #1  0x00007fe1cbd8c862 abort (libc.so.6 + 0x26862)
                #2  0x00007fe1cc12a86a _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9686a)
                #3  0x00007fe1cc136d3a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa2d3a)
                #4  0x00007fe1cc136da7 _ZSt9terminatev (libstdc++.so.6 + 0xa2da7)
                #5  0x00007fe1cc13704e __cxa_throw (libstdc++.so.6 + 0xa304e)
                #6  0x00007fe1cc12d9bc _ZSt20__throw_system_errori (libstdc++.so.6 + 0x999bc)
                #7  0x00007fe1cc163e42 _ZNSt6thread4joinEv (libstdc++.so.6 + 0xcfe42)
                #8  0x0000558934579fae n/a (./ProjectIgnis/EDOPro + 0x179fae)
```
Some additional data:
Kernel: Linux 5.11.7
Distro: Arch Linux
Mono JIT compiler version 6.12.0

**Comment by FelixRilling** [comment]
Additional Notes:
- It can be reproduced for me consistently.
- Weirdly enough, clicking  "Host" on the screen and Canceling, clicking "Join" shows the regular error message instead of crashing

**Comment by edo9300** [comment]
Should be fixed in https://github.com/edo9300/edopro/commit/b8c9b85fe764546573150b8d9d3cc8d6789a867c
