### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by nfitzen** [edo9300/edopro#209]
YGOPro appears to be licensed under [`GPL-2.0-only`] (or at least it should be assumed that way) because the only version number specified is 2.0 within GitHub (based on [the tree as of the latest commit](https://github.com/Fluorohydride/ygopro/tree/2cedcbb93b857a7372f436d3985ae517554e3f19)). Is this program infringing on the copyright of YGOPro, or was there some sort of exception granted? I couldn't find a license notice in the source files indicating it's [`GPL-2.0-or-later`].

[`GPL-2.0-only`]: https://spdx.org/licenses/GPL-2.0-only.html
[`GPL-2.0-or-later`]: https://spdx.org/licenses/GPL-2.0-or-later.html

(While I would like to believe I know a bit about copyright and free software licensing, IANAL and this is not legal advice. Edit: This issue is meant to bring attention to a possible issue, but consult with an attorney for any more information.)

**Comment by edo9300** [comment]
There is no License version specified anywhere in that repository, and [as stated in the `LICENSE` file](https://github.com/Fluorohydride/ygopro/blob/2cedcbb93b857a7372f436d3985ae517554e3f19/LICENSE#L246-L248), if no version is specified then any GPL version can be used.

One of the main reasons we changed the License was because certain parties were violating the freedoms that we granted to users. We didn't like that and wanted to avoid it as much as possible. We chose AGPL because we wanted to guarantee that the use of this code in server environments would remain free and open.

**Comment by nfitzen** [comment]
> if no version is specified then any GPL version can be used

Upon further consideration, I guess "specify" would necessarily entail, well, being specific. I was completely wrong.
I knew about that clause in [GPL-2.0 &sect; 9], but I didn't really consider that just including the GPL-2.0 license text doesn't count as specifying the license version.

[GPL-2.0 &sect; 9]: https://www.gnu.org/licenses/gpl-2.0.html#section9

> We chose AGPL because we wanted to guarantee that the use of this code in server environments would remain free and open.

I wasn't really talking about using the AGPL besides indirectly through GPL-1.0-or-later -> GPL-3.0-or-later compatibility, but, since it was mentioned, I agree with the decision to license the core under the AGPL. The main complication is that client users playing each other would need to disclose Corresponding Source if one of them modifies the program. This could be handled with a [&sect; 7][AGPLv3 section 7] exception, and I feel like that should be done, if possible.

[AGPLv3 section 7]: https://www.gnu.org/licenses/agpl-3.0.html#section7

I'm closing this issue because, well, it's not exactly an issue. Another issue could be opened if anyone wishes to try to implement the possible &sect; 7 exception I mentioned. (This issue was about licensing compatibility with YGOPro's licensing.) IANAL, so I most likely can't come up with one.

**Comment by nfitzen** [comment]
I'm reopening this because, after more thought (wow I'm really indecisive), just including the license text would certainly count as specifying a version.

This needs to be addressed and should probably be taken up with the developers of YGOPro.

**Comment by sagehane** [comment]
Speaking of GPL compliance, doesn't it go against GPL to lack proper build instructions? Will edit this comment with more details after I can backup my statement.

To quote the [front page of the wiki](https://github.com/edo9300/edopro/wiki):
>TODO: explain how to build the core independently.

>TODO: describe build process with Discord RPC TODO: describe build process with sound backends

>N.B.: documentation is kind of outdated - sorry but I have limited time

(I ask because I believe I attempted to build EDOPro for Linux like 2-3 times over the past year or so and failed miserably. Although I'm admittedly not familiar with CMake, Premake, and other tools)

**Comment by nfitzen** [comment]
@sagehane while reproducible builds and free documentation are important for free software, I don't believe the GPL requires it. You just have to be able to build it from source with generally available tools.

[AGPL-3.0 &sect; 1] defines "Corresponding Source":

> The "Corresponding Source" for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities. However, it does not include the work's System Libraries, or general-purpose tools or generally available free programs which are used unmodified in performing those activities but which are not part of the work.

[AGPL-3.0 &sect; 1]: https://www.gnu.org/licenses/agpl-3.0.html#section1

**Comment by nfitzen** [comment]
> One of the main reasons we changed the License was because certain parties were violating the freedoms that we granted to users. We didn't like that and wanted to avoid it as much as possible. We chose AGPL because we wanted to guarantee that the use of this code in server environments would remain free and open.

@edo9300 if you didn't want server code to be published, then why not take advantage of the AGPL's compatibility with the GPL? &sect; 14 of both [GPL-3.0][GPL-3.0 s14] and [AGPL-3.0][AGPL-3.0 s14] states that you can combine code under the GPLv3 with the AGPLv3. This would also allow the upstream YGOPro to reuse the client code but would allow ocgcore and the scripts to be AGPL.

[GPL-3.0 s14]: https://www.gnu.org/licenses/gpl-3.0.html#section14
[AGPL-3.0 s14]: https://www.gnu.org/licenses/agpl-3.0.html#section14

You could just license the client program under [`GPL-2.0-or-later`] and license ocgcore under [`AGPL-3.0-or-later`], and distribute the combined work under the terms provided by GPL and AGPL v3 &sect; 14.

This would also address 

[`GPL-2.0-or-later`]: https://spdx.org/licenses/GPL-2.0-or-later.html
[`AGPL-3.0-or-later`]: https://spdx.org/licenses/AGPL-3.0-or-later.html
