### ISSUE TITLE
on dependency phase for installation, unable use travis get-linux-vcpkg-cache.sh

### ISSUE THREAD

**Issue by sukrosono** [edo9300/edopro#215]
sorry for assuming that is runnable/invokable .
Further more I can't find the `./ocgcore/travis/install-lua.sh linux` , is the wiki installation outofdate?

the result for variable not set
![ksnip_edopro_20210907-211226](https://user-images.githubusercontent.com/3001652/132359839-ac1142d3-9643-40ec-b2dc-b8a443ef2bea.png)

where is the repo for the mobile app (apk) ?

**Comment by sukrosono** [comment]
I am doing `git clone https://github.com/edo9300/ygopro-core ocgcore` since it empty directory. But it's not the main problem.

**Comment by sukrosono** [comment]
I assume i should invoke `premake5.lua` so i can get the file and call 
```./premake5 gmake2 --vcpkg-root=YOUR_VCPKG_FOLDER
make -Cbuild -j2```
but it yeild:
![ksnip_lua_prob20210907-214234](https://user-images.githubusercontent.com/3001652/132366204-0a88c579-6f4c-47e3-89b7-ee6fb52e17f2.png)

**Comment by edo9300** [comment]
> is the wiki installation outofdate?

yes, the wiki for now is outdated so the best way to build is to follow the ci scripts
> I assume i should invoke premake5.lua so i can get the file and call

You run the ``premake5`` executable, you don't run the ``premake5.lua`` script

**Comment by sukrosono** [comment]
hey thanks, I just download from the mega the Linux binary. Sadly I just remove all the local repo.
thanks for developing this. 

Sorry, I am missing the discord, I just send you a friend request on dc.
I got a couple Idea and questions for you.

As I remember premake5 executable is not there, I am looking for the premake5 folder also.
Thanks for the fast response. Great job.

**Comment by edo9300** [comment]
You have to manually download the premake5 binary from their site

**Comment by sukrosono** [comment]
I don't know the future doi-sh after it. I cant send you a message on DC, I think we/you should make official distribution to F-droid and flatpak. I hope this sounds interesting to you :smiley:
