### ISSUE TITLE
A error of a update 

### ISSUE THREAD

**Issue by Azra12el** [edo9300/edopro#216]
Well I don't if it's me or I miss some information but when the new support of the magician came and other came to is doesn't show up but other players do have. So I don't and I went to YouTube to see is something is wrong and one of the videos says " the three bards has to be 100%" and I only have two I don't if I have some problems I hope I'm not making problems. A I'm using android 

![Screenshot_20210910-230023](https://user-images.githubusercontent.com/90495804/132938274-2a7fa74d-8162-4025-b5ce-782cf921584e.jpg)

**Comment by edo9300** [comment]
This is not the place to report those issues, report them in the discord server in the appropriate channel (after reading the FAQ)
