### ISSUE TITLE
Error: reference 'refs/heads/master' not found

### ISSUE THREAD

**Issue by AmrKhalid666** [edo9300/edopro#219]
Hello.

Originally, EDOPro's update was stuck at 5%. I copied the files from an old saved folder and managed to push it to 80%, but then it gave me this error:
The repo https://github.com/ProjectIgnis/DeltaUtopia couldn't be cloned.
Error: reference 'refs/heads/master' not found
![image](https://user-images.githubusercontent.com/28936711/142277386-c535464a-8f5b-4a82-8dae-dd1d8b24a761.png)
What do?

**Comment by edo9300** [comment]
Please ask for help about these issues on our discord server (and follow the FAQ steps there)
