### ISSUE TITLE
Can I kindly request adding the Speed Duel GX Box skills to EDOPro?

### ISSUE THREAD

**Issue by irisobserving** [edo9300/edopro#233]
Sorry, I'm not sure where else to ask this (not really used to Github, ahaha).

For the last few months, I've been working on a custom metagame for some friends, and I've decided to give one of the decks the "Middle Age Mechs" skill from the Speed Duel GX box to help bring its consistency more on par with the other decks.

Unfortunately, while the skills from the Battle City box are in EDOPro, the GX ones aren't, which is a little unfortunate! (Plus, it'd mean I could play more Speed Duels with friends, which would also be nice.)

Thank you for reading this! EDOPro is a huge blessing, and I'm so glad this simulator exists, by the way - keep up the great work!

**Comment by edo9300** [comment]
This isn't the right repository to talk about this stuff. In any case those cards are being worked on, but being from speed duel and such they have lower priority, and also, like with everything else, there is no ETA.
