### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by centell** [edo9300/edopro#236]
Failed to update EdoPro 39.3.2 on MacOS.

Erorr Message is:
```
Error: reference 'refs/head/main' not found
```

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19484641/171439811-d56a9be1-2034-4439-9bd8-b898a050af81.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19484641/171439897-c7a849df-a133-446b-8c94-3dafb3cd281b.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/19484641/171439983-69c19d27-80c3-482d-b2d1-ad2f991dfd72.png">

**Comment by edo9300** [comment]
ask for help with these issues in our discord server, in any case, the solution for that issue is the question 19 in the faq channel in the server.
