### ISSUE TITLE
Show/Hide the Windbot/FeelingLucky Decks in the Deck Edit and Host Duel

### ISSUE THREAD

**Issue by TPM5934** [edo9300/edopro#238]
Is it possible to add these ticks to the game menus, so as to show / hide the decks for the Windbot and Feeling Lucky? also if possible add in the host to show / hide the player's Decks in the windbot section, as per the example pics I send (the pics are modified by me to understand better, unfortunately I am not able to do it by myself for edopro).
![main menu](https://user-images.githubusercontent.com/80354859/173223416-2ea7ea5c-96f6-42bc-baa9-653d4decbc95.png)

![host WLAN+AI](https://user-images.githubusercontent.com/80354859/173223403-20b0bb6d-f31d-4a5f-8d1f-4e3b215dfe45.png)
.

**Comment by edo9300** [comment]
There's no "feeling lucky decks" to hide, as those are the user's decks. As for showing ai decks, that's very low priority and not even really worth adding for now since all those decks would be unusable in the end both because of the current meta and also because of the current banlists.

**Comment by TPM5934** [comment]
I understand, then to do this, you can't make the "feeling lucky" performer respond to decks with a certain prefix like this: "feeling lucky_Battlin Boxer" and check as I said to show / hide decks with suffix "feeling lucky _...." can you do this?
