### ISSUE TITLE
Cards with art variants getting incorrectly displayed as legal with a custom banlist that has them banned

### ISSUE THREAD

**Issue by diamonddudetcg** [edo9300/edopro#240]
My custom banlist contains the following line

`90590304 -1 -- Number 41: Bagooska the Terribly Tired Tapir`

EDOPRO shows this

![image](https://user-images.githubusercontent.com/1720747/173931802-f6799998-b88f-4523-a667-ab6ecd41ed1b.png)

**Comment by edo9300** [comment]
https://github.com/edo9300/edopro/commit/a0cfca32040fdda31e183015bfc9b8b3273a4359 whitelist handling got updated with aliased cards, now you'll have to explicitly list them in the whitelist as well (in your case you're banning the alt art only, not the original one, that is 90590303, in which case both would be properly banned).

**Comment by diamonddudetcg** [comment]
@edo9300 

Yeah, I understand that.

However both versions of Bagooska share the same ID, and only one of those is getting correctly banned.

![image](https://user-images.githubusercontent.com/1720747/173933026-e05cd957-382b-423d-b73e-3c447b204453.png)

![image](https://user-images.githubusercontent.com/1720747/173933061-52ece2d9-b6f4-4b88-8971-0462340a2cc0.png)

**Comment by edo9300** [comment]
Internally the "original" has the id 90590303, the alternate art has the id 90590304 and is aliased to 90590303, in your banlist you're banning 90590304, thus only the alternate art is being affected.
