### ISSUE TITLE
White noise on Android

### ISSUE THREAD

**Issue by IngEyn** [edo9300/edopro#253]
When I am running EDOPro on my Samsung Galaxy S7 with Android 8 I notice the speaker putting out a white-noise-like sound.

The sound itself is audible regardless of the master audio volume and even with the volume being at 0%. It changes a little when turning the volume up - it becomes more like a hummung noise when between 0% and 100% (and the closer I am to 50%); at 0% and 100% it appears to sound the same.

The noise is audible with both sound and music being turned on even though it is less noticeable due to the music playing but it is also audible with only one of those options turned on as well as with none of them turned on.

I do not know when it started since it is not too noticeable but I assume it has always been like this. There was nothing I could do to fix this and it still happens whenever I launch EDOPro and only ends a few seconds after I have exited and completely closed the app through the 'task manager' so that it does not allocate any RAM.

**Comment by edo9300** [comment]
I use a library (SFML) that uses another library (openal-soft) to handle sound, unfortunately I don't have much control on what is done by those libraries, but I can confirm that i tested it and I too can hear that white noise. (I've done a quick search on those libraries' issue trackers but there wasn't anything related to this issue.)
