### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kriki8254** [edo9300/edopro#254]
Error: C:/Users/Kiki/Documents/Ignis/edopro/irrlicht/premake5.lua:16: attempt to concatenate a nil value

**Comment by edo9300** [comment]
It errors out because the environment variable ```DXSDK_DIR``` is not set (which should point to your direct SDK installation). Either you install the direct SDK or you compile with the flag to disable it ```no-direct3d```

**Comment by Kriki8254** [comment]
Thanks it works. But its kindof misleading saying its optional.

**Comment by Kriki8254** [comment]
Nvm i just can't read it says to add a parameter if you didn't download.
