### ISSUE TITLE
Can't build game

### ISSUE THREAD

**Issue by Eduardo-Vilas-Boas** [edo9300/edopro#256]
Installed Git Bash, Visual Studio with C++ support

Tried following instructions in Wiki, and also complemented with others: here is the final script (final_build_script.sh - txt to bypass security)

[build_final_product.txt](https://github.com/edo9300/edopro/files/10320856/build_final_product.txt)

Right now, I am stuck on this error -> "Failed to load strings!"

**Comment by Eduardo-Vilas-Boas** [comment]
![imagem](https://user-images.githubusercontent.com/43207746/209991852-42fbe875-ce10-42fd-aa11-0dc9d3ec2b5b.png)

**Comment by Eduardo-Vilas-Boas** [comment]
On file gframe/data_handler.cpp

**Comment by Eduardo-Vilas-Boas** [comment]
The files ARE there.

**Comment by Eduardo-Vilas-Boas** [comment]
![Capture](https://user-images.githubusercontent.com/43207746/209992228-d5458475-c455-47b4-ba4d-ecda25540dc3.PNG)

**Comment by edo9300** [comment]
The solution was correctly built, the error you're getting is that it doesn't find its config files, by default the program will change its working directory to the location of the exe, you can change this by adding a command line argument to the project settings, ``Debug->ygopro's debug properties->Debug->Command line arguments`` and you put the working directory as ``-C "path"``
![immagine](https://user-images.githubusercontent.com/18705342/209992503-8686c556-c312-4744-a02c-d55adf450926.png)

**Comment by Eduardo-Vilas-Boas** [comment]
It is working now. Thank you.
