### ISSUE TITLE
No more Talented AI bots in Rush duel mode?

### ISSUE THREAD

**Issue by YUGi-atem** [edo9300/edopro#259]
The AI bots of Rush duel is missing? the only left is not wise bot that spam what can he use any time. I want the 2 Healing Jam and the other bots too with specific AI for their deck. Why did you remove the 2 bots? . Please add other wise bot if you will just remove the wiser bot in specific deck. I'm playing EDOpro because of them.

**Comment by edo9300** [comment]
Ni bits were removed, I suppose you're on android, in that case do a clean reinstall of the game and it should copy back the right files, anyways for those issues use the discord server as they're unrelated to the program itself that is hosted on this repo
