### ISSUE TITLE
I:P masquerna  summoning link 6 when only max link 5

### ISSUE THREAD

**Issue by ShreemJ** [edo9300/edopro#260]
[2023-03-16 15-38-09.yrpx.zip](https://github.com/edo9300/edopro/files/10992717/2023-03-16.15-38-09.yrpx.zip)

In this replay I have i:p 2 link 2 and 1 monster. I use i:p and it summons firewall dragon singularity but it is a link 2 and 3 more monsters which makes link 5 not link 6 which firewall dragon singularity is.

**Comment by NaimSantos** [comment]
1) This is the repository for the client, not a potential problems with script and/or the core.
2) For card bugs, reports must be submitted in [our Discord server](https://discord.gg/ygopro-percy 
).
3 ) You might want to revisit the rulebook:
![image](https://user-images.githubusercontent.com/26061438/225675672-512a2abf-d3bc-498e-bcd6-0f5e61ded45f.png)

On the field you had:
- I:P Masquerena (Link 2)
- Cyberse Wicckid (Link 2)
- Linguriboh (Link 1)
- Matmetch Subtraction
2 + 2 + 1 + 1 = 6
Firewall Dragon Singularity is a link 6, so there is no problem here.
