### ISSUE TITLE
Randomised Deck

### ISSUE THREAD

**Issue by ZenitH-AT** [edo9300/edopro#268]
A "random" button in the deck editor to generate a legal deck of random cards, with the minimum main deck size and maximum extra and side deck size could be fun.

The use case would mostly be for playing against friends doing the same as a challenge, so adding this as a lobby option might be more appropriate.

**Comment by NaimSantos** [comment]
The idea might sound interesting to you but it's impractial. Although generating a valid deck (at least 40 cards, at most 60, etc.)  sounds trivial, there is no way to guarantee it will be playable. For example, you could get a deck with 30 Ritual monsters and 30 lv5 or higher Normal monsters or a deck full of archetypal cards that you can never use. We have more than 19000 possible cards that could be added to the deck; it's not feasible to implement this.
