### ISSUE TITLE
Can Edo play  with YGO? What is the  server address of edo?or host imformation

### ISSUE THREAD

**Issue by sdfest** [edo9300/edopro#272]
my friend use ygopro，can i use edo play with him？
thankyou

**Comment by edo9300** [comment]
yes, edopro supports ygopro servers, you'll have to connect to whatever server your friend is connecting to through lan mode

**Comment by sdfest** [comment]
yes,i can connect his server.
But he realy want to connect my server, but i dont konw edo server is what ,just like this ⬇


sorry to bother you ,but i really want konw this.thanks!
&nbsp;


L
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Edoardo ***@***.***&gt;; 
发送时间: 2024年7月15日(星期一) 凌晨0:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [edo9300/edopro] Can Edo play  with YGO? What is the  server address of edo?or host imformation (Issue #272)














 
yes, edopro supports ygopro servers, you'll have to connect to whatever server your friend is connecting to through lan mode

**Comment by edo9300** [comment]
Edopro servers aren't supported by ygopro, as they're incompatible, so your only way is to duel on ygopro servers, that are supported by both

**Comment by sdfest** [comment]
alright, thank you very much edo is a very creative software. Mdpro3 is a branch of ygopro2 developed by Chinese players. It supports english. I suggest you try it. It adds special effects for master duels. It would be great if the animation card effects of edopro can be added to it. Anyway, thank you very much!




L
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edo9300/edopro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月15日(星期一) 凌晨0:10
***@***.***&gt;;
抄送： ***@***.******@***.***&gt;；
主题: &nbsp;Re: [edo9300/edopro] Edo 可以玩 YGO 吗？edo 的服务器地址是什么？或主机信息 (问题 #272)





 
ygopro 不支持 Edopro 服务器，因为它们不兼容，所以你唯一的办法就是在 ygopro 服务器上决斗，因为 ygopro 服务器都支持
  
—
直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您之所以收到此邮件，是因为您是该主题的作者。消息ID ：< ***@***.*** &gt;
