### ISSUE TITLE
The big settings window and more configurability

### ISSUE THREAD

**Issue by kevinlul** [edo9300/edopro#98]
Settings are crammed. Time to make a separate window!
- [x] Accessible by gear icon in the bottom left corner of the main screen
- [x] Accessible by keyboard shortcut any time
- [ ] Settings in the pane also show up in the window and are synced

Settings to add to the pane
- [x] Button to show settings window

General refactoring
- [x] Separate Config class from `game.h`
- [ ] Use the WindBot/WindBotPanel approach to separating logic and UI in additional compilation units, hopefully

Settings to keep in the pane, in this order
- Mute opponents
- Mute spectators
- Quick animation
- Hide chain buttons
- Auto chain order
- No chain delay
- Auto MZone placement
- Auto SZone placement
- Randomize auto placement
- [x] Reordered
- [ ] Add event bindings to separate UI from state

Settings to move to the window exclusively
- [x] Show FPS
- [x] Enable music
- [x] Music volume slider
- [x] Enable sound effects and chants
- [x] Sound volume slider
- [x] Skin selection
- [x] Reload current skin
- [x] if sound backend loading failed, put a message here in place of the audio settings

Additional settings to add to the window
- [x] ctrlClickIsRMB
- [x] Show archetypes in deck edit
- [x] Show card scopes and passcodes in deck edit
- [x] Draw field spell arts
- [x] Scale background
- [x] Accurate background resize (PC only)
- [x] FPS cap
- [x] Script error level (nothing, console, log to file, stacktrace, etc.)
- [x] Filter WindBot for current Master Rule
- [x] Save replays for puzzles?
- [ ] Warn on leaving deck edit with unsaved changes?
- [ ] ~~Hide gear icon~~
- [x] Fullscreen?
- [ ] Reset LAN settings to default
- [ ] Reset all settings to default
- [x] Show console (Windows only; requires restart)
- [ ] Use DirectX (Windows only; requires restart)
- [x] VSync (requires restart)
- [x] Antialiasing (requires restart)
- [ ] ~~Fonts and font sizes? (requires restart)~~
- [x] DPI scale (requires restart)
- [x] Reported compatibility version

Additional persistence
- [x] WindBot mute
- [x] WindBot throw rock
- [x] WindBot selected deck
- [x] Last server
- [x] LAN duel mode
- [x] LAN best of
- [x] LAN relay
- [x] LAN time limit
- [x] LAN Master Rule
- [x] LAN check deck
- [x] LAN shuffle deck
- [x] LAN starting LP
- [x] LAN starting hand
- [x] LAN cards per draw
- [x] LAN extra rules

Sysstrings to externalize after
- [x] Settings window label
- [x] No audio static text
- [x] Skin label
- [x] Reload Skin
- [x] "none" skin name
- [x] Hide passcode scope

**Comment by kevinlul** [comment]
Progress started in the [settings](https://github.com/edo9300/ygopro/tree/settings) branch.

**Comment by NaimSantos** [comment]
Not sure exactly what you mean by ` Toggling detailed stacktrace for scripts` but could the `Error Log` be also added to the settings? With the options it has: disabled, via in game message, via text file or both

**Comment by kevinlul** [comment]
It's an option to enable or disable the new stack trace feature. It can be merged with the classic errorlog setting.
